### ISSUE TITLE
validates uniqueness of fails with UUID pk

### ISSUE THREAD

**Issue by SampsonCrowley** [PhilWaldmann/openrecord#48]
```
{ [SQLError: error: select count(*) as "count" from "accounts" where "accounts"."email" = $1 and "accounts"."id" != $2 - invalid input syntax for uuid: "1"]
  message:
   { error: invalid input syntax for uuid: "1"
       at Connection.parseE (/home/samps/sites/personal/dus/office.downundersports.com/node/node_modules/pg/lib/connection.js:567:11)
       at Connection.parseMessage (/home/samps/sites/personal/dus/office.downundersports.com/node/node_modules/pg/lib/connection.js:391:17)
```

**Comment by SampsonCrowley** [comment]
I don't know where that "1" would be coming from. this is on create of a brand new record

**Comment by SampsonCrowley** [comment]
the id is being set on new

```
newAccount = Account.new({email: account.email.toLowerCase(), password: account.password})
console.log(newAccount); #=> `<Account {id:"1" email:"myemail@email.email" password:"password" athlete_id:null created_at:null updated_at:null}>`
```

**Comment by SampsonCrowley** [comment]
found it. I'll put together a PR

**Comment by SampsonCrowley** [comment]
fixed in https://github.com/PhilWaldmann/openrecord/pull/49

**Comment by SampsonCrowley** [comment]
You can close this once everything's merged in

**Comment by PhilWaldmann** [comment]
Perfekt! Thx

I'll release the new version tomorrow
